In [70]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers
from sklearn import preprocessing
import glob

import os
from torch.utils.data import Dataset
import tensorflow as tf

In [71]:
# Get CSV files list from a folder
train_path = './ProcessedDatasets/Knot_Tying/TrainSet'
test_path = './ProcessedDatasets/Knot_Tying/TestSet'
train_csv_files = glob.glob(train_path + "/*.csv")
test_csv_files = glob.glob(test_path + "/*.csv")

# Read each CSV file into DataFrame
# This creates a list of dataframes
train_df_list = (pd.read_csv(file) for file in train_csv_files)
test_df_list = (pd.read_csv(file) for file in test_csv_files)

# Concatenate all DataFrames
train_df   = pd.concat(train_df_list, ignore_index=True)
test_df   = pd.concat(test_df_list, ignore_index=True)

In [72]:
lb = preprocessing.LabelBinarizer()



train_labels= train_df.pop('label')
train_features = train_df

test_labels= test_df.pop('label')
test_features = test_df

train_labels = lb.fit_transform(train_labels)
test_labels = lb.fit_transform(test_labels)






[[0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 ...
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]]
[[0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 ...
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]]


In [74]:
print(train_labels.shape)
print(test_labels.shape)

(41013, 6)
(10845, 6)
